### ISSUE TITLE
Reporte de mockup

### ISSUE THREAD

**Issue by Blanca-estela-valerio-rivero** [SistemasTecTlaxiaco/actividad-1-practicaprototipo-confident-students#2]
https://www.figma.com/file/10gDLRDhXwRNZ5UjxEu04K/Untitled?type=design&node-id=0-1&mode=design&t=KhVFpYcfb8tu2h6r-0
[Reporte de mockup- Confident Students.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-practicaprototipo-confident-students/files/14188704/Reporte.de.mockup-.Confident.Students.pdf)
 
Integrantes del equipo:
 García Santiago Sandy Marissa
Sarmiento Ruiz Edgar Mauricio
 Valerio Rivero Blanca Estela

**Comment by IrvinSanchez-dev** [comment]
Dado a los criteros de evaluacion ustedes obtuvieron 18.4% de 20%

** Le faltaron mas ilustraciones en el reporte de practica, ya que solo colocaron 13 de 20, lo cual fue un valor de 17 puntos de 25.
** De igual manera en la conclusion eran 12 lineas, y solo tenia 11, pero se le tomo los 25 puntos. :D

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
